name: Lint - Prettier

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: creyD/prettier_action@v4.6
        with:
          prettier_options: --check --write **/*.{ts,tsx,js,md}
          dry: true