name: Lint - Revive

on:
  pull_request:
  push:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "revive.toml"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Revive Action
        uses: morphy2k/revive-action@v2.7.8
        # with:
        #   config: revive.toml
